### PR TITLE
Hotseat: Ignore messages which include mentions to other users

### LINKED ISSUE #2: [Feature request] Only talk to Limmy in the hotseat!
Hi @DaftLimmy , I know you know this because you're a pro-coder. But for others, this is the issues section of github which can track bugs that need fixing or suggesting new features. Like a to do list. Anyway here is the 'issue':

If someone in the hotseat @ replies to another user, that message should be ignored by the hotseat.

### PR DESCRIPTION
**Pull request by Jeddunk**
Fixes #2!

When hotseat is on, messages that contain mentions to other users should be ignored.

As soon as #1 gets merged, I can change my PR accordingly.

### CODE REVIEW

**Comment by DaftLimmy** [comment]
Thanks. But how's about one wee tweak. I'd only like the message to be prevented from displaying if it BEGINS with an @ to another user.

For example, somebody might say to me "Don't ask me, Limmy, ask @Jeddunk", and I'd like to show.

Also, could you check to see if (context.username == hotSeatUser) before checking if the message has an @? It's more efficient.

**Comment by Jeddunk** [comment]
I've made the changes as requested. It should now only look for user mentions at the beginning of the message, and I've also merged the if functions for efficiency.

**Comment by adeydev** [comment]
Could you maybe add a comment above the if statement? The code is self documenting to a point but nothing beats a wee comment.

**Comment by adeydev** [comment]
Could you make it a triple equals too? 

I like this pull request btw. Focussed on one thing so it’s easy to review.

**Comment by adeydev** [comment]
Thanks for updates. It looks good.

**Pull request merged**
