### PR TITLE
Use twitch v2 emotes (supports animated emotes)

### PR DESCRIPTION
**Pull request by Gantonator**
Just switched the twitch emote url to V2 from V1, so now animated emotes will work.

### CODE REVIEW

**Comment by Rcjuk** [comment]
Has these been throughly tested?

**Comment by Gantonator** [comment]
https://user-images.githubusercontent.com/18462104/122923928-1acd1800-d35d-11eb-8bf8-d1c1e3354583.mp4

**Comment by Rcjuk** [comment]
Thank you Lord Blahemtee

**Review by zaccolley — APPROVED** [review]
I need to do this for my code too, nice one

**Review by DaftLimmy — APPROVED** [review]

**Pull request merged**
